projects:
  commerce:
    schemaPath: amplify/backend/api/commerce/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/amplify.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
